blueprint:
  name: SMART Doorbell
  description: >
   The SMART doorbell blueprint. 
   
   Flash a light, send TTS to speakers or send phone notifications all when the doorbell is pressed.

   Please define either a doorbell event or a binary sensor that detects when the doorbell is pressed.
  domain: automation
  author: "https://github.com/J-shw"
  homeassistant:
    min_version: 2024.6.0
  input:
    trigger_settings:
      name: "Trigger Settings *"
      icon: mdi:bell-ring-outline
      description: Select the trigger settings for the doorbell automation.
      collapsed: true
      input:
        doorbell_event:
          name: Doorbell Event
          description: The event that triggers the doorbell automation.
          default: []
          selector:
            entity:
              filter:
                - domain: event

        doorbell_binary_sensor:
          name: Doorbell Binary Sensor
          description: The binary sensor that detects when the doorbell is pressed.
          default: []
          selector:
            entity:
              filter:
                - domain: binary_sensor
        
        doorbell_image_entity:
          name: Doorbell Image Entity (Optional)
          description: The camera entity that provides an image of the doorbell when triggered.
          default: []
          selector:
            entity:
              filter:
                - domain: camera
    
    notification_settings:
      name: Notification Settings
      icon: mdi:bell-outline
      description: Configure notification settings for the doorbell automation.
      collapsed: true
      input:
        notify_enabled:
          name: Enable Notifications
          description: Enable or disable notifications when the doorbell is triggered.
          default: false
          selector:
            boolean:
        notify_with_doorbell_image:
          name: Include Doorbell Image in Notification
          description: Include an image from the doorbell camera in the notification.
          default: false
          selector:
            boolean:
        notify_title:
          name: Notification Title
          description: The title of the notification to be sent when the doorbell is triggered.
          default: "Doorbell Alert"
          selector:
            text:
        notify_message:
          name: Notification Message
          description: The message to be sent when the doorbell is triggered.
          default: "Someone is at the door."
          selector:
            text:
        
        notify_mobile_device:
          name: Mobile Device Notification Target
          description: The device to send the notification to. (e.g., mobile device, tablet, etc.)
          default: []
          selector:
            device:
              integration: mobile_app
        notify_target:
          name: General Notification Target
          description: The target to send the notification to. (e.g., Alexa, notify group, etc.)
          default: []
          selector:
            entity:
              domain: notify

    light_settings:
      name: Lights
      icon: mdi:lightbulb-outline
      description: Select the lights to flash when the doorbell is triggered.
      collapsed: true
      input:
        target_light:
          name: Lights
          description: The lights to flash when the doorbell is triggered.
          default: []
          selector:
            target:
              entity:
                - domain: light
        light_flash_count:
          name: Light Flash Count
          description: The number of times the lights should flash when the doorbell is triggered.
          default: 4
          selector:
            number:
              min: 2
              max: 10
              step: 2
        light_flash_duration_seconds:
          name: Light Flash Duration
          description: The duration of each light flash in seconds.
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5
              step: 0.1
    
    tts_settings:
      name: TTS Settings
      icon: mdi:account-voice
      description: Configure text-to-speech settings for the doorbell automation.
      collapsed: true
      input:
        tts_enabled:
          name: Enable TTS
          description: Enable or disable text-to-speech notifications.
          default: false
          selector:
            boolean:
        tts_message:
          name: TTS Message
          description: The message to be spoken when the doorbell is triggered.
          default: "Someone is at the door."
          selector:
            text:
        tts_target_speaker:
          name: TTS Target Speaker
          description: The speaker to play the TTS message on.
          default: []
          selector:
            entity:
              domain: media_player

    time_settings:
      name: "Time Settings *"
      icon: mdi:clock-outline
      description: Select the time-related settings for when the automation should run.
      collapsed: true
      input:
        after_time:
          name: After Time
          description: The time after which the automation can run.
          default: "00:00:00"
          selector:
            time:
        
        before_time:
          name: Before Time
          description: The time before which the automation can run.
          default: "23:59:59"
          selector:
            time:
        
        day_of_week:
          name: Day of Week
          description: The days of the week on which the automation can run.
          default:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          selector:
            select:
              multiple: true
              mode: list
              options:
                - value: mon
                  label: Monday
                - value: tue
                  label: Tuesday
                - value: wed
                  label: Wednesday
                - value: thu
                  label: Thursday
                - value: fri
                  label: Friday
                - value: sat
                  label: Saturday
                - value: sun
                  label: Sunday
  
    presence_settings:
      name: "Presence Settings *"
      icon: mdi:account-check-outline
      description: Configure presence detection settings for the doorbell automation. 
      collapsed: true
      input:
        people_to_check:
          name: People to Check
          description: Select the people to check for presence before triggering the automation.
          default: []
          selector:
            entity:
              domain: person

variables:
  doorbell_event: !input doorbell_event
  doorbell_binary_sensor: !input doorbell_binary_sensor
  doorbell_image_entity: !input doorbell_image_entity

  people_to_check: !input people_to_check

  after_time: !input after_time
  before_time: !input before_time
  day_of_week: !input day_of_week

  light_flash_count: !input light_flash_count
  light_flash_duration_seconds: !input light_flash_duration_seconds
  target_light: !input target_light

  tts_enabled: !input tts_enabled
  tts_message: !input tts_message
  tts_target_speaker: !input tts_target_speaker

  notify_enabled: !input notify_enabled
  notify_with_doorbell_image: !input notify_with_doorbell_image
  notify_title: !input notify_title
  notify_message: !input notify_message
  notify_target: !input notify_target
  notify_mobile_device: !input notify_mobile_device


triggers:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input doorbell_event
    id: use_event
  - platform: state
    entity_id: !input doorbell_binary_sensor
    from: "off"
    to: "on"
    id: use_binary

conditions:
  - condition: time
    after: !input after_time
    before: !input before_time
    weekday: !input day_of_week
  
  - condition: template
    value_template: >
      {% set people = [entities] if entities is string else entities %}
      {% if people == none or people == [] or people == [''] %}
        true
      {% else %}
        {{ states.person | selectattr('entity_id', 'in', people) | selectattr('state', 'eq', 'home') | list | length > 0 }}
      {% endif %}
      
action:
  - if:
      - condition: template
        value_template: "{{ target_light != {} or target_light != [] }}"
    then:
      - repeat:
          count: !input light_flash_count
          sequence:
            - action: light.toggle
              target: !input target_light
            - delay:
                seconds: !input light_flash_duration_seconds

  - if:
      - condition: template
        value_template: "{{ tts_enabled }}"
    then:
      - action: tts.speak
        target:
          entity_id: !input tts_target_speaker
        data:
          media_player_entity_id: !input tts_target_speaker
          message: !input tts_message
  
  - if:
      - condition: template
        value_template: "{{ notify_enabled and (notify_target != {} or notify_target != []) }}"
    then:
      - action: notify.send_message
        target:
          entity_id: !input notify_target
        data:
          title: !input notify_title
          message: !input notify_message
  
  - if:
      - condition: template
        value_template: "{{ notify_enabled and (notify_mobile_device != {} or notify_mobile_device != []) }}"
    then:
      - device_id: !input notify_mobile_device
        domain: mobile_app
        type: notify
        title: !input notify_title
        message: !input notify_message
        data: >-
          {% if notify_with_doorbell_image and (doorbell_image_entity != {} or doorbell_image_entity != []) %}
            {{ {'image': state_attr(doorbell_image_entity, 'entity_picture')} }}
          {% else %}
            {{ {} }}
          {% endif %}