blueprint:
  name: SMART Doorbell
  description: >
   The SMART doorbell blueprint. 
   
   Flash a light, send TTS to speakers or send phone notifications all when the doorbell is pressed.

   Please define either a doorbell event or a binary sensor that detects when the doorbell is pressed.
  domain: automation
  input:
    trigger_settings:
      name: "Trigger Settings *"
      icon: mdi:bell-ring-outline
      description: Select the trigger settings for the doorbell automation.
      collapsed: true
      input:
        doorbell_event:
          name: Doorbell Event (Optional)
          description: The event that triggers the doorbell automation.
          default: []
          selector:
            entity:
              filter:
                - domain: event

        doorbell_binary_sensor:
          name: Doorbell Binary Sensor (Optional)
          description: The binary sensor that detects when the doorbell is pressed.
          default: []
          selector:
            entity:
              filter:
                - domain: binary_sensor
    
    light_settings:
      name: Lights
      icon: mdi:lightbulb-outline
      description: Select the lights to flash when the doorbell is triggered.
      collapsed: true
      input:
        target_light:
          name: Lights
          description: The lights to flash when the doorbell is triggered.
          selector:
            target:
              entity:
                - domain: light
        light_flash_count:
          name: Light Flash Count
          description: The number of times the lights should flash when the doorbell is triggered.
          default: 3
          selector:
            number:
              min: 1
              max: 10
              step: 1
        light_flash_duration:
          name: Light Flash Duration
          description: The duration of each light flash in seconds.
          default: 0.5
          selector:
            number:
              min: 0.1
              max: 5
              step: 0.1
    
    tts_settings:
      name: TTS Settings
      icon: mdi:volume-high-outline
      description: Configure text-to-speech settings for the doorbell automation.
      collapsed: true
      input:
        tts_enabled:
          name: Enable TTS
          description: Enable or disable text-to-speech notifications.
          default: false
          selector:
            boolean:
        tts_message:
          name: TTS Message
          description: The message to be spoken when the doorbell is triggered.
          default: "Someone is at the door."
          selector:
            text:
        tts_target_speaker:
          name: TTS Target Speaker
          description: The speaker to play the TTS message on.
          selector:
            entity:
              domain: media_player

    time_settings:
      name: "Time Settings *"
      icon: mdi:clock-outline
      description: Select the time-related settings for when the automation should run.
      collapsed: true
      input:
        after_time:
          name: After Time
          description: The time after which the automation can run.
          default: "00:00:00"
          selector:
            time:
        
        before_time:
          name: Before Time
          description: The time before which the automation can run.
          default: "23:59:59"
          selector:
            time:
        
        day_of_week:
          name: Day of Week
          description: The days of the week on which the automation can run.
          default:
            - mon
            - tue
            - wed
            - thu
            - fri
            - sat
            - sun
          selector:
            select:
              multiple: true
              mode: list
              options:
                - value: mon
                  label: Monday
                - value: tue
                  label: Tuesday
                - value: wed
                  label: Wednesday
                - value: thu
                  label: Thursday
                - value: fri
                  label: Friday
                - value: sat
                  label: Saturday
                - value: sun
                  label: Sunday

variables:
  doorbell_event: !input doorbell_event
  doorbell_binary_sensor: !input doorbell_binary_sensor

  after_time: !input after_time
  before_time: !input before_time
  day_of_week: !input day_of_week

  light_flash_count: !input light_flash_count
  light_flash_duration: !input light_flash_duration
  target_light: !input target_light
  tts_enabled: !input tts_enabled
  tts_message: !input tts_message
  tts_target_speaker: !input tts_target_speaker

triggers:
  - platform: event
    event_type: state_changed
    event_data:
      entity_id: !input doorbell_event
    id: use_event
  - platform: state
    entity_id: !input doorbell_binary_sensor
    from: "off"
    to: "on"
    id: use_binary

conditions:
  - condition: time
    after: !input after_time
    before: !input before_time
    weekday: !input day_of_week

actions:
  - action: >
      # Light Flashing Action
      if target_light:
        for i in range(light_flash_count):
          service: light.toggle
          target:
            entity_id: target_light
          delay:
            seconds: light_flash_duration
      
      # TTS Action
      if tts_enabled and tts_target_speaker:
        service: tts.google_translate_say
        target:
          entity_id: tts_target_speaker
        message:
          value: tts_message